version: "2"

services:
  mongodb:
    build:
      context: ./docker
      dockerfile: Dockerfile-mongodb
    restart: always
    volumes:
      - ./docker/db:/data/db
    environment:
      - AUTH=no

  server:
    build:
      context: ./docker
      dockerfile: Dockerfile-server
    restart: always
    volumes:
      - ./:/sugarizer-repo
    links:
      - mongodb
    ports:
      - 8039:8039

  http:
    build:
      context: ./docker
      dockerfile: Dockerfile-http
    restart: always
    volumes:
      - ./:/sugarizer-repo
    ports:
      - 80:80
    links:
      - server
